version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: ordermanagement-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=SuaSenha@123
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - ordermanagement-network

  mongodb:
    image: mongo:7.0
    container_name: ordermanagement-mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=SuaSenha@123
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ordermanagement-network

  redis:
    image: redis:7-alpine
    container_name: ordermanagement-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ordermanagement-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: ordermanagement-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=SuaSenha@123
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ordermanagement-network

volumes:
  sqlserver_data:
  mongodb_data:
  redis_data:
  rabbitmq_data:

networks:
  ordermanagement-network:
    driver: bridge
